Repository coderedcorp/coderedcms, pull requests merged in 2019-08, with the labels that each got.

#229 Fix migration problems introduced to master branch
  coderedcms/models/page_models.py
  coderedcms/models/snippet_models.py
  coderedcms/models/wagtailsettings_models.py
  coderedcms/project_template/basic/website/migrations/0001_initial.py
  coderedcms/project_template/sass/website/migrations/0001_initial.py
Labels: PR: awaiting review

#227 Pipeline improvements
  azure-pipelines.yml
  ci/compare-artifacts.ps1
  ci/make-docs.ps1
  ci/run-flake8.ps1
  ci/run-tests.ps1
  ci/run_artifacts.ps1
  ci/run_autopep8.ps1
  ci/run_black.ps1
  docs/Makefile
  docs/contributing/index.rst
  docs/make.bat
  setup.py
Labels: PR: awaiting review

#226 Wagtail 2.6 upgrade
  .gitignore
  coderedcms/models/page_models.py
  coderedcms/static/coderedcms/css/codered-admin.css
  coderedcms/static/coderedcms/css/codered-editor.css
  coderedcms/templates/wagtailadmin/base.forked.html
  coderedcms/templates/wagtailadmin/base.html
  coderedcms/templates/wagtailadmin/shared/main_nav.html
  coderedcms/wagtail_flexible_forms/edit_handlers.py
  docs/releases/v0.16.0.rst
  setup.py
Labels: PR: awaiting review

#238 Updating github templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/community.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  docs/contributing/index.rst
Labels: PR: Awaiting Review

#246 Fixing AMP template error
  coderedcms/__init__.py
  coderedcms/templates/coderedcms/pages/base.amp.html
  docs/releases/index.rst
  docs/releases/v0.16.1.rst
Labels: PR: Awaiting Review

#249 Unit test AMP pages
  .gitignore
  coderedcms/models/tests/test_page_models.py
Labels: PR: Awaiting Review

#243 Form field type now defaults to single line text, making 500 error im…
  coderedcms/forms.py
  coderedcms/project_template/basic/website/migrations/0001_initial.py
  coderedcms/project_template/sass/website/migrations/0001_initial.py
  docs/releases/index.rst
  docs/releases/v0.17.0.rst
Labels: PR: Awaiting Review

#216 Partial correct [BUG] #202 - Correct a Navbar snippets to support multisite coderedcorp
  coderedcms/migrations/0016_layoutsettings_navbar_name.py
  coderedcms/migrations/0017_auto_20190629_2321.py
  coderedcms/models/snippet_models.py
  coderedcms/models/wagtailsettings_models.py
  coderedcms/templates/coderedcms/snippets/navbar.html
  coderedcms/templatetags/coderedcms_tags.py
Labels: PR: Awaiting Author

#234 Test 404 page and built-in URLs
  .gitignore
  coderedcms/tests/test_urls.py
Labels: PR: Awaiting Author
